### ISSUE TITLE
Updates for latest LBRY / SDK

### ISSUE THREAD

**Issue by tzarebczan** [stellartux/plugin.video.lbry#2]
Hey, wondering if you still plan on supporting this project. We'd love to chat and see how we can incentivize more development/features!

**Comment by stellartux** [comment]
Sure, I haven't looked at this project for a while, but I had been meaning to get back to it at some point.

**Comment by tzarebczan** [comment]
There's big API changes happening..maybe a good time will be when we enable data streaming (not streaming/live video..yet) which will allow better storage management and less data on disk. Send us your LBC address when you get a chance :) (hello@lbry.com)
